export const productImages = [
  { src: '/productImage/01ナプキン.webp', alt: '紙ナプキン' },
  { src: '/productImage/02おしぼり.webp', alt: '紙おしぼり' },
  { src: '/productImage/03箸袋.webp', alt: '箸袋' },
  { src: '/productImage/04コースター.webp', alt: 'コースター' },
  { src: '/productImage/05エプロン.webp', alt: 'エプロン' },
  { src: '/productImage/06テーブルマット.webp', alt: 'テーブルマット' },
  { src: '/productImage/07天ぷら敷き紙.webp', alt: '天ぷら敷き紙' },
  { src: '/productImage/08造花.webp', alt: '造花' },
  { src: '/productImage/09爪楊枝.webp', alt: '爪楊枝' },
  { src: '/productImage/10バーガー袋.webp', alt: 'バーガー袋' },
  { src: '/productImage/11アルミ容器.webp', alt: 'アルミ容器' },
  { src: '/productImage/12保冷剤.webp', alt: '保冷剤' },
  { src: '/productImage/13テーパートレー.webp', alt: 'テーパートレー' },
  { src: '/productImage/14紙コップ.webp', alt: '紙コップ' },
  { src: '/productImage/15ストロー.webp', alt: 'ストロー' },
  {
    src: '/productImage/16プラスチックスプーン.webp',
    alt: 'プラスチックスプーン・フォーク',
  },
  { src: '/productImage/17マプカスプーン.webp', alt: 'MAPKAスプーン・フォーク' },
  { src: '/productImage/18木製スプーン.webp', alt: '木製スプーン・フォーク' },
  { src: '/productImage/19パルプモールド.webp', alt: 'パルプモールド' },
  { src: '/productImage/20FM弁当容器.webp', alt: 'FM弁当容器' },
  { src: '/productImage/21FMホイルケース.webp', alt: 'ホイルケース' },
  { src: '/productImage/22FMフィルムケース.webp', alt: 'フィルムケース' },
  { src: '/productImage/23FM紙ケース.webp', alt: '紙ケース' },
  { src: '/productImage/24シリコンペーパーカップ.webp', alt: 'シリコンペーパー' },
  { src: '/productImage/25V-BOX.webp', alt: 'おせちV-BOX' },
  { src: '/productImage/26結べる紙風呂敷.webp', alt: '結べる紙風呂敷' },
  { src: '/productImage/27クッキングホイル.webp', alt: 'クッキングホイル' },
  { src: '/productImage/28クッキングシート.webp', alt: 'クッキングシート' },
  { src: '/productImage/29キッチンペーパー.webp', alt: 'キッチンペーパー' },
  { src: '/productImage/30カウンタークロス.webp', alt: 'カウンタークロス' },
  { src: '/productImage/31リチクラーレ.webp', alt: 'ペーパータオル・リチクラーレ' },
  { src: '/productImage/32マスク.webp', alt: 'マスク' },
  { src: '/productImage/33ライスネット.webp', alt: 'ライスネット' },
  { src: '/productImage/34会計伝票.webp', alt: '会計伝票' },
  { src: '/productImage/35ディスポタオル.webp', alt: 'ディスポタオル' },
  { src: '/productImage/36フルーツキャップ.webp', alt: 'フルーツキャップ' },
];
